name: cinnabar

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: final
    restart: unless-stopped
    environment:
      GITHUB_APP_ID: $GITHUB_APP_ID
      GITHUB_PRIVATE_KEY: $GITHUB_PRIVATE_KEY
      GITHUB_WEBHOOK_SECRET: $GITHUB_WEBHOOK_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  vault:
    build:
      context: vault
    command: server
    restart: unless-stopped
    volumes:
      - vault-data:/vault/file:rw
    cap_add:
      - IPC_LOCK

  nginx:
    depends_on:
      - backend
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    restart: on-failure:1
    environment:
      CERTBOT_EMAIL: $CERTBOT_EMAIL
      CERTBOT_DOMAINS: >
        app.cinnabar-ci.dev
        vault.cinnabar-ci.dev
    volumes:
      - certificates:/etc/letsencrypt:rw
      - /etc/letsencrypt/renewal-hooks
    
volumes:
  vault-data:
  certificates:
