name: cinnabar

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: final
    restart: unless-stopped
    environment:
      GITHUB_APP_ID: $GITHUB_APP_ID
      GITHUB_PRIVATE_KEY: $GITHUB_PRIVATE_KEY
      GITHUB_WEBHOOK_SECRET: $GITHUB_WEBHOOK_SECRET
      DATABASE_URL: /var/lib/cinnabar/database.db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - database:/var/lib/cinnabar/:rw

  nginx:
    depends_on:
      - backend
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: $CERTBOT_EMAIL
      CERTBOT_DOMAINS: >
        app.cinnabar-ci.dev
    volumes:
      - certificates:/etc/letsencrypt:rw
      - /etc/letsencrypt/renewal-hooks
    
volumes:
  certificates:
  database:
