# syntax=docker/dockerfile:1

ARG RUST_VERSION=1.77.2
ARG APP_NAME=backend

FROM rust:${RUST_VERSION}-alpine AS build
ARG APP_NAME
WORKDIR /app

RUN apk add --no-cache clang lld musl-dev git

RUN --mount=type=bind,source=backend,target=backend \
    --mount=type=bind,source=Cargo.toml,target=Cargo.toml \
    --mount=type=bind,source=Cargo.lock,target=Cargo.lock \
    --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
cargo build --package ${APP_NAME} --locked --release && \
cp ./target/release/${APP_NAME} /bin/server

FROM alpine:3.18 AS final

# ARG UID=10001
# RUN adduser \
#     --disabled-password \
#     --gecos "" \
#     --home "/nonexistent" \
#     --shell "/sbin/nologin" \
#     --no-create-home \
#     --uid "${UID}" \
#     appuser
# USER appuser

COPY --from=build /bin/server /bin/

EXPOSE 42069

CMD ["/bin/server"]
