[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
jsonwebtoken = "9.3.0"
octocrab = "0.38.0"
serde = "1.0.197"
thiserror = "1.0.59"
url = "2.5.0"
